version: "3"

services:
  app:
    image: coupons-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coupons-app
    ports:
      - "80:80"
    volumes:
      - local-db:/usr/src/app/server/db

volumes:
  local-db: